name: Swift2
on:
  [ push ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: npm init -y
    - name: install
      run: npm install request
    - name: run
      run: node xcuitest.js