name: Testing

on:
  [push]

jobs:
  thanks:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: install
      - run: npm install
      
      - name: test
      - run: node xcuitest.js
